In [2]:
import torch
x=torch.arange(12)
print(x)
print(x.shape)  #张量形状
print(x.numel()) #标量，元素种数

X=x.reshape(3,4)
print(X)
print(X.numel())
print(X.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
12
torch.Size([3, 4])


In [3]:
torch.tensor([[2,1,3,4],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [4]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y  #**运算符是求幂函数运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [8]:
x=torch.arange(12,dtype=torch.float32).reshape((3,4))
y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)   #生成x,y并使用cat方法将其拼接起来

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [9]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [10]:
x.sum()

tensor(66.)

In [12]:
#广播机制，扩展张量
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
print(a)
print(b)
print(a+b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [13]:
print(x[-1])
print(x[1:3])

tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [14]:
x[1,2]=9  #局部赋值
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
#内存相关
before =id(y)
y=y+x
id(y)==before  #更新值之后重新分配了地址

False

In [16]:
z = torch.zeros_like(y)
print('id(z):',id(z))
z[:]=x+y  
print('id(z):',id(z))  #原地操作，没有改变内存

id(z): 2810894756144
id(z): 2810894756144


In [17]:
A=x.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [18]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)