In [6]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')

with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') #列名
    f.write('NA,Pave,127500\n') #每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

print(os.path

<module 'ntpath' from 'D:\\Anaconda\\envs\\dl_env\\lib\\ntpath.py'>


In [11]:
import pandas as pd
data =pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [18]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
numeric = inputs.select_dtypes(include='number').columns
inputs[numeric] = inputs[numeric].fillna(inputs[numeric].mean())
print(inputs)


   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [19]:
inputs =pd.get_dummies(inputs,dummy_na=True,dtype=int) #one-hot编码,dtype重要
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [20]:
import torch

x,y = torch.tensor(inputs.values),torch.tensor(outputs.values)
x,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [22]:
a=torch.arange(12)
b=a.reshape(3,4) #b为a的view，更改b会同步修改a
b[:] =2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)