In [2]:
#向量，一维标量
#向量正交 a*b=∑ai*bi=0
#矩阵乘法：前行乘后列对应项相加
#范数：衡量一个向量大小的标准，用向量的元素本身来计算向量本身大小
"""
L1范数：|X|1 =∑|Xi|
L2范数：|X|2 = √(Σxᵢ²)
L3范数：|X|3 =max(Xi)
"""
#特殊矩阵
"""
对称矩阵：Aij=Aji
反对称矩阵: Aij=-Aji
正定矩阵:乘以任何一个行向量和列向量都大于等于0的矩阵
"""

'\n对称矩阵：Aij=Aji\n反对称矩阵: Aij=-Aji\n正定矩阵:乘以任何一个行向量和列向量都大于等于0的矩阵\n'

In [3]:
import torch

#标量用一维张量表示
x = torch.tensor([3.0])
y = torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [4]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

In [6]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

In [8]:
A = torch.arange(20).reshape(4,5)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [9]:
A.T #矩阵转置

tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

In [10]:
#对称矩阵
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B==B.T #判断是否为对称矩阵

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [12]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [13]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone() #分配新的内存
print(A)
print(B)
print(f"A")
print(f"A+B={A+B}")
print(id(A)==id(B)) #A，B内存不一致

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
A
A+B=tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
False


In [14]:
#矩阵乘法
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [15]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [16]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [17]:
A=torch.arange(20*2).reshape(2,5,4)
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780))

In [18]:
A_sum_axis0=A.sum(axis=0)
A_sum_axis0,A_sum_axis0.reshape

(tensor([[20, 22, 24, 26],
         [28, 30, 32, 34],
         [36, 38, 40, 42],
         [44, 46, 48, 50],
         [52, 54, 56, 58]]),
 <function Tensor.reshape>)

In [19]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1 ,A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]),
 torch.Size([2, 4]))

In [20]:
A.sum(axis=[0,1])

tensor([180, 190, 200, 210])

In [21]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [36]:
A = torch.arange(20*2,dtype=torch.float32).reshape(2,5,4)
A.shape,A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

In [37]:
A.mean(axis=0,dtype=torch.float32),A.shape,A.sum()/A.numel()

(tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]]),
 torch.Size([2, 5, 4]),
 tensor(19.5000))

In [38]:
sum_A=A.sum(axis=1,keepdims=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

In [39]:
#广播机制：维数必须相同
A/sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

In [40]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [41]:
#向量点积计算
y=torch.ones(4,dtype=torch.float32)
print(x)
print(y)
print(torch.dot(x,y))
print(torch.sum(x*y))

tensor([0., 1., 2., 3.])
tensor([1., 1., 1., 1.])
tensor(6.)
tensor(6.)


In [42]:
A.shape,x.shape
torch.mv(A[0],x)
#Matrix Vector Multiplication

tensor([ 14.,  38.,  62.,  86., 110.])

In [44]:
B = torch.ones(4,3)
torch.mm(A[0],B) #mm的元素必须都是矩阵

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [51]:
#L2范数
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [52]:
#L1范数
torch.abs(u).sum()

tensor(7.)

In [53]:
#F范数（针对矩阵）:矩阵元素的平方和的平方根
torch.norm(torch.ones((4,9)))

tensor(6.)

In [57]:
import torch
a=torch.ones(2,5,4)
a.shape

torch.Size([2, 5, 4])

In [64]:
print(a.sum().shape)
print(a.sum(axis=0).shape)
print(a.sum(axis=1).shape)
print(a.sum(axis=2,keepdims=True).shape)#保持维数

torch.Size([])
torch.Size([5, 4])
torch.Size([2, 4])
torch.Size([2, 5, 1])
